site:
  title: GeoDB documentation
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://geodb.io/docs
content:
  sources:
  - url: .
    branches: HEAD
    start_path: /
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
